### ISSUE TITLE
Release octomap_ros into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [OctoMap/octomap_ros#11]
Would you mind releasing `octomap_ros` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 13 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by wxmerkt** [comment]
Done - cf. https://github.com/ros/rosdistro/pull/24544 :-)
