### ISSUE TITLE
Cannot find code API in conversion.h with ROS Noetic

### ISSUE THREAD

**Issue by zichunxx** [OctoMap/octomap_ros#16]
Hi! 

When I want to use the function `octomap::pointcloudPCLToOctomap` [listed in this document](http://docs.ros.org/en/diamondback/api/octomap_ros/html/namespaceoctomap.html#a664e1133e32f2d2ee3f099b8bd96c89f), I find there is no corresponding function in my ocotomap_ros.

I installed this lib by `sudo apt-get install ros-noetic-****`.

Did I miss something?

Thanks!

**Comment by wxmerkt** [comment]
Hi @QUIlToT,
This function has been removed 9 years ago - cf. https://github.com/OctoMap/octomap_ros/commit/dbc7256722ed0027cb6618d475ef416dcf59632d - the documentation you checked is for [Diamondback](http://wiki.ros.org/diamondback).
