### ISSUE TITLE
compile error on OSX Mavericks: explicit instantiation cannot have a storage class

### ISSUE THREAD

**Issue by markusachtelik** [OctoMap/octomap_ros#3]
```
octomap_ros/src/conversions.cpp:46:23: error: explicit instantiation cannot have a storage class
```

it looks like clang doesn't like the `static` keyword in https://github.com/OctoMap/octomap_ros/blob/master/src/conversions.cpp#L45 and L46. After removing `static`in both lines, everything compiles.  

Not sure what the intention behind these two lines was. I can also open a PR with the changes if that makes it easier.

**Comment by ahornung** [comment]
That looks like a copy&paste error from conversions.h. I assume you did not have to change anything in the header itself, only the cpp?

**Comment by markusachtelik** [comment]
thanks for the fast answer! Yes, it's only the cpp.

**Comment by ahornung** [comment]
Fix released. Thanks!
